### ISSUE TITLE
Tweaks for - Add Vehicle page

### ISSUE THREAD

**Issue by TKaija** [wizimara/chariots#1]
**TASKS include;**

- [x] 1. Should indicate on all forms all throughout the site, inputs that are required and those that are not.
- [ ] 2. Select car owner = Should automatically select logged in user as car owner.
- [x] 3. Currently system allows duplicate Car number plates. what will be the format for number plates. [UBG893T] or [UBD 437H] With space or no space. Keep in mind a basis of country in searches.
- [x] 4. Add drop down for Fuel type = Petrol, Diesel, Hybrid, Electric .
- [x] **5. Tracker Status (To be removed for NOW - Clients will use a third party service provider )**
- [ ] 6. Should have only Comprehensive Insurance = Yes or No option. Should capture - Name of Insurance company, Insurance policy number. (All these should be required and marked with an asterix)
- [x] 7. Currently allows past dates as insurance expiry date = It shouldn't do this.
- [x] 8. After a car has been saved, and you return to edit it, Vehicle status select button defaults to Active even when the car is currently disabled. Tracker Status defaults to NO, Car's Transmission defaults to Auto, Car's Insurance  Defaults to Third Party.
- [ ] 9. Vehicle Location should use a google map address selection.
- [x] 10. Vehicle location selected does not show when one edits already existing car entry.
- [x] 11. Why are images only entered after the car has first been saved, if this is the only option can we make the process more user friendly or streamlined.
- [x] 12. Car owner MUST be able to select one of the images as a "Featured Image" for display purposes on front end as the car image to use.
- [x] 13. Vehicle image caption (Should be removed - Not needed).
- [ ] 14. We need to ensure images uploaded do not have text over them. Can we find a way to do this automatically or it will be a manual process.
- [x] 15. Layout of page after car image has been added - Has the submit changes button above that of submitting new images.
- [ ] 16. You should be able to add more than one image at a single time. i.e. 3 or more images at once.
- [ ] 17. When selecting car features, can we allow multiple select instead of adding one at a time.
- [ ] 18. What options do we have available for Image sizes compression and auto cropping.
- [x] 19. When there is an error on page (e.g. because of missing data) on refresh, vehicle features selected are not returned.
- [x] 20. Status should be changed to - Enable Vehicle and placed at the very top of the page (And should use an On/Off button). If ON the car is visible in front end listings, if OFF the car is not visible in listings.
- [x] 21. All - Vehicles List page. Table Header details are too many. Hide - **ID, Tracker, Transmission, Fuel Type, Insurance Type,** Include - **Category**
- [x] 22. All - Vehicles List page. ID, Make, Model, Color, Location - **Should Not Be Links** - Same for View Vehicles Page
- [x] 23. All - Vehicles List page. Search function at top left of page - Currently only filters/searches by the vehicle ID. Should be able to filter by any of the header details or even more advanced i.e by one or many at once.
- [ ] 24. Duplicate car categories still accepted
