### ISSUE TITLE
Chariots Frontend/Website Content Pages

### ISSUE THREAD

**Issue by TKaija** [wizimara/chariots#16]
**TASKS**

- [x] 1. Design and Build Chariots Homepage

- [x] 2. Build How it works page

- [ ] 3. Build - Vehicle registration requirements page

- [ ] 4. Build Car care essentials page

- [ ] 5. Build - About us page

- [x] 6. Build - Get help page

- [ ] 7. Build - FAQs, Terms and Privacy pages

- [ ] 8. Build - List your car page

- [ ] 9. Build - Earn more page

- [ ] 10. Build - Social Media Pages
