### ISSUE TITLE
Search plugin ad functionality

### ISSUE THREAD

**Issue by TKaija** [wizimara/chariots#17]
**Tasks**

- [ ] 1. Location information should ensure the search results can show me which available cars are nearest or furthest from my location

- [ ] 2. I should not be able to book from dates that have already expired or past.

- [ ] 3. Advanced search should help me finesse my search to greater detail. E.g Cars with a Carrier, particular color, sat nav, e.t.c
