### ISSUE TITLE
Search results page as seen by renters on front-end

### ISSUE THREAD

**Issue by TKaija** [wizimara/chariots#18]
**Tasks**

- [ ] 1. Human understandable error message should be shown when search results are empty.

- [ ] 2. Should use a loading animation combined with the word "Searching" when search results are being generated.

- [ ] 3. Include a search form on search results page so renters shouldn't have to go back to homepage to adjust search results.

- [ ] 4. Have images show in equivalent width and height on search results page
