### ISSUE TITLE
Editing of Pricing information for cars

### ISSUE THREAD

**Issue by TKaija** [wizimara/chariots#2]
**Tasks**

**Need to do more research on pricing models including whether or not to charge renters trip insurance**

- [x] 1. Details on this page are currently not editable once saved including discounts, delivery cost. Please confirm that all these details can be edited.

- [x] 2. Currently the date range of a cars availability cannot be edited.

- [ ] 3. Is the discount an amount or is it applied as a percentage (Help text may be helpful here to clarify)
