### ISSUE TITLE
View vehicle page

### ISSUE THREAD

**Issue by TKaija** [wizimara/chariots#23]
**TASKS include;**

- [x] After a new vehicle has been added to, on saving the vehicle the user should be redirected to the view of that vehicle he/she has added.
- [ ] Add colors to adding a vehicle so that name of color and the look of color are visible.
- [x] Remove - Tracker
- [x] Status - To be changed to **Enable Car** and placed at top of table or list. Preferably an ON/OFF button.
- [x] Do not allow duplicate imports of car makes and car models.
- [ ] The view will then allow the user to add other details to the car including:- images (multi select), features (multi select). 
- [ ] Other details to added from this page include - Pricing, car schedule or days of availability in calendar, car usage rules and restrictions e.t.c. However the existing car schedules page can remain active as well - it does not necessarily need to be removed.
- [x] Disable links on Make, Model, Color, and Location.
- [x] Remove ID from tables for Car Images and Car Features.
- [ ] Car Features Table - The view feature link currently leads to the main system Car Features entries.
