### ISSUE TITLE
Car owner dashboard features

### ISSUE THREAD

**Issue by TKaija** [wizimara/chariots#3]
**Tasks**
As a car owner I would like to keep a close eye on my Bookins, Earnings, trip history e.t.c.

- [ ] 1. View listed cars and their details, receive notifications from CR about any issues that need my urgent attention.

- [ ] 2. Earnings  per day, week, month, year.

- [ ] 3. Compare performance of cars under my account e.g by number of booking requests, earnings.

- [ ] 4. View history of all past jobs.
